name: Basic workflow
on: 
  push:

jobs:
  test:
    name: "Jest test"
    runs-on: ubuntu-latest
    services:
      pdns-auth:
        image: powerdns/pdns-auth-49:latest
        ports:
          - 8081:8081
        env:
          PDNS_AUTH_API_KEY: "apikey"
        # volumes:
        #   - ./pdns.conf:/etc/powerdns/pdns.conf
        options: >-
          --health-cmd curl http://127.0.0.1:8081/api/v1
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container: 
      image: node:22
      env:
        NODE_ENV: development
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install deps
        run: npm ci
      - name: Run tests
        run: npm run test