name: Basic workflow
on: 
  push:

jobs:
  test:
    name: "Jest test"
    runs-on: ubuntu-latest
    container: 
      image: node:22
      env:
        NODE_ENV: development
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install deps
        run: npm ci
      - name: Run tests
        run: npm run test